---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    metadata:
      labels:
        tag: {{ .Values.nginx.name }}
    spec:
      initContainers:
        - name: update-index
          image: google/cloud-sdk
          command: ['sh', '-c', "gsutil cp gs://ae_hiring_files/index.html /usr/share/nginx/html/index.html"]
      containers:
        - name: nginx
          image: {{ .Values.nginx.image | quote }}
          ports:
            - containerPort: {{ .Values.nginx.port }}

  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      tag: {{ .Values.nginx.name }}

# --------------------------------

--- 
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: '{"default": "nginx-backend-config"}'
  name: nginx-service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.nginx.port }}
  selector:
    tag: {{ .Values.nginx.name }}

# --------------------------------

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: "nginx-backend-config"
spec:
  securityPolicy:
    name: {{ quote .Values.cloud_armor_policy_name }}
  timeoutSec: 1800
  # For better security, IAP should be configured
  # iap:
  #   enabled: {{ .Values.iap.enable_iap }}
  #   oauthclientCredentials:
  #     secretName: {{ .Values.iap.oauth_client_credentials_k8s_secret_name }}